name: f1_info
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas==2.2.3
      - pre-commit==4.5.0
      - langchain==1.0.8
      - langchain-community==0.4.1
      - langchain-huggingface==1.1.0
      - fastf1==3.6.1
      - tqdm==4.66.1
      - fastapi==0.101.1
      - uvicorn>=0.32.0
      - h11>=0.14
      - langchain-experimental==0.4.0
      - duckdb==1.4.1
      - duckdb-engine==0.17.0
      - glob2==0.7
      - sentence-transformers==5.1.2
